// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: internal/api/proto/kudo.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KudoAPI_Apply_FullMethodName            = "/kudo.KudoAPI/Apply"
	KudoAPI_Remove_FullMethodName           = "/kudo.KudoAPI/Remove"
	KudoAPI_GetStatus_FullMethodName        = "/kudo.KudoAPI/GetStatus"
	KudoAPI_ListNodes_FullMethodName        = "/kudo.KudoAPI/ListNodes"
	KudoAPI_ListApplications_FullMethodName = "/kudo.KudoAPI/ListApplications"
	KudoAPI_ScaleApplication_FullMethodName = "/kudo.KudoAPI/ScaleApplication"
)

// KudoAPIClient is the client API for KudoAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KudoAPIClient interface {
	Apply(ctx context.Context, in *ApplyRequest, opts ...grpc.CallOption) (*ApplyResponse, error)
	Remove(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*RemoveResponse, error)
	GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error)
	ListApplications(ctx context.Context, in *ListAppsRequest, opts ...grpc.CallOption) (*ListAppsResponse, error)
	ScaleApplication(ctx context.Context, in *ScaleRequest, opts ...grpc.CallOption) (*ScaleResponse, error)
}

type kudoAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewKudoAPIClient(cc grpc.ClientConnInterface) KudoAPIClient {
	return &kudoAPIClient{cc}
}

func (c *kudoAPIClient) Apply(ctx context.Context, in *ApplyRequest, opts ...grpc.CallOption) (*ApplyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyResponse)
	err := c.cc.Invoke(ctx, KudoAPI_Apply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kudoAPIClient) Remove(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*RemoveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveResponse)
	err := c.cc.Invoke(ctx, KudoAPI_Remove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kudoAPIClient) GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, KudoAPI_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kudoAPIClient) ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNodesResponse)
	err := c.cc.Invoke(ctx, KudoAPI_ListNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kudoAPIClient) ListApplications(ctx context.Context, in *ListAppsRequest, opts ...grpc.CallOption) (*ListAppsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAppsResponse)
	err := c.cc.Invoke(ctx, KudoAPI_ListApplications_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kudoAPIClient) ScaleApplication(ctx context.Context, in *ScaleRequest, opts ...grpc.CallOption) (*ScaleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScaleResponse)
	err := c.cc.Invoke(ctx, KudoAPI_ScaleApplication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KudoAPIServer is the server API for KudoAPI service.
// All implementations must embed UnimplementedKudoAPIServer
// for forward compatibility.
type KudoAPIServer interface {
	Apply(context.Context, *ApplyRequest) (*ApplyResponse, error)
	Remove(context.Context, *RemoveRequest) (*RemoveResponse, error)
	GetStatus(context.Context, *StatusRequest) (*StatusResponse, error)
	ListNodes(context.Context, *ListNodesRequest) (*ListNodesResponse, error)
	ListApplications(context.Context, *ListAppsRequest) (*ListAppsResponse, error)
	ScaleApplication(context.Context, *ScaleRequest) (*ScaleResponse, error)
	mustEmbedUnimplementedKudoAPIServer()
}

// UnimplementedKudoAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKudoAPIServer struct{}

func (UnimplementedKudoAPIServer) Apply(context.Context, *ApplyRequest) (*ApplyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Apply not implemented")
}
func (UnimplementedKudoAPIServer) Remove(context.Context, *RemoveRequest) (*RemoveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Remove not implemented")
}
func (UnimplementedKudoAPIServer) GetStatus(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedKudoAPIServer) ListNodes(context.Context, *ListNodesRequest) (*ListNodesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNodes not implemented")
}
func (UnimplementedKudoAPIServer) ListApplications(context.Context, *ListAppsRequest) (*ListAppsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListApplications not implemented")
}
func (UnimplementedKudoAPIServer) ScaleApplication(context.Context, *ScaleRequest) (*ScaleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ScaleApplication not implemented")
}
func (UnimplementedKudoAPIServer) mustEmbedUnimplementedKudoAPIServer() {}
func (UnimplementedKudoAPIServer) testEmbeddedByValue()                 {}

// UnsafeKudoAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KudoAPIServer will
// result in compilation errors.
type UnsafeKudoAPIServer interface {
	mustEmbedUnimplementedKudoAPIServer()
}

func RegisterKudoAPIServer(s grpc.ServiceRegistrar, srv KudoAPIServer) {
	// If the following call panics, it indicates UnimplementedKudoAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KudoAPI_ServiceDesc, srv)
}

func _KudoAPI_Apply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KudoAPIServer).Apply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KudoAPI_Apply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KudoAPIServer).Apply(ctx, req.(*ApplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KudoAPI_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KudoAPIServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KudoAPI_Remove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KudoAPIServer).Remove(ctx, req.(*RemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KudoAPI_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KudoAPIServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KudoAPI_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KudoAPIServer).GetStatus(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KudoAPI_ListNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KudoAPIServer).ListNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KudoAPI_ListNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KudoAPIServer).ListNodes(ctx, req.(*ListNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KudoAPI_ListApplications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAppsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KudoAPIServer).ListApplications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KudoAPI_ListApplications_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KudoAPIServer).ListApplications(ctx, req.(*ListAppsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KudoAPI_ScaleApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScaleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KudoAPIServer).ScaleApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KudoAPI_ScaleApplication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KudoAPIServer).ScaleApplication(ctx, req.(*ScaleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KudoAPI_ServiceDesc is the grpc.ServiceDesc for KudoAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KudoAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kudo.KudoAPI",
	HandlerType: (*KudoAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Apply",
			Handler:    _KudoAPI_Apply_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _KudoAPI_Remove_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _KudoAPI_GetStatus_Handler,
		},
		{
			MethodName: "ListNodes",
			Handler:    _KudoAPI_ListNodes_Handler,
		},
		{
			MethodName: "ListApplications",
			Handler:    _KudoAPI_ListApplications_Handler,
		},
		{
			MethodName: "ScaleApplication",
			Handler:    _KudoAPI_ScaleApplication_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/api/proto/kudo.proto",
}
