// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: internal/api/proto/kudo.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApplyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	YamlContent   string                 `protobuf:"bytes,1,opt,name=yaml_content,json=yamlContent,proto3" json:"yaml_content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyRequest) Reset() {
	*x = ApplyRequest{}
	mi := &file_internal_api_proto_kudo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyRequest) ProtoMessage() {}

func (x *ApplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_proto_kudo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyRequest.ProtoReflect.Descriptor instead.
func (*ApplyRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_proto_kudo_proto_rawDescGZIP(), []int{0}
}

func (x *ApplyRequest) GetYamlContent() string {
	if x != nil {
		return x.YamlContent
	}
	return ""
}

type ApplyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyResponse) Reset() {
	*x = ApplyResponse{}
	mi := &file_internal_api_proto_kudo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyResponse) ProtoMessage() {}

func (x *ApplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_proto_kudo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyResponse.ProtoReflect.Descriptor instead.
func (*ApplyResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_proto_kudo_proto_rawDescGZIP(), []int{1}
}

func (x *ApplyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ApplyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RemoveRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	YamlContent string                 `protobuf:"bytes,1,opt,name=yaml_content,json=yamlContent,proto3" json:"yaml_content,omitempty"`
	// When true, continue removing cluster state and routes if workloads are already gone.
	ForceMissingWorkloads bool `protobuf:"varint,2,opt,name=force_missing_workloads,json=forceMissingWorkloads,proto3" json:"force_missing_workloads,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *RemoveRequest) Reset() {
	*x = RemoveRequest{}
	mi := &file_internal_api_proto_kudo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRequest) ProtoMessage() {}

func (x *RemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_proto_kudo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRequest.ProtoReflect.Descriptor instead.
func (*RemoveRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_proto_kudo_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveRequest) GetYamlContent() string {
	if x != nil {
		return x.YamlContent
	}
	return ""
}

func (x *RemoveRequest) GetForceMissingWorkloads() bool {
	if x != nil {
		return x.ForceMissingWorkloads
	}
	return false
}

type DependencyInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AppName        string                 `protobuf:"bytes,1,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	DependentApp   string                 `protobuf:"bytes,2,opt,name=dependent_app,json=dependentApp,proto3" json:"dependent_app,omitempty"`
	Reason         string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	SharedResource string                 `protobuf:"bytes,4,opt,name=shared_resource,json=sharedResource,proto3" json:"shared_resource,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DependencyInfo) Reset() {
	*x = DependencyInfo{}
	mi := &file_internal_api_proto_kudo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DependencyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DependencyInfo) ProtoMessage() {}

func (x *DependencyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_proto_kudo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DependencyInfo.ProtoReflect.Descriptor instead.
func (*DependencyInfo) Descriptor() ([]byte, []int) {
	return file_internal_api_proto_kudo_proto_rawDescGZIP(), []int{3}
}

func (x *DependencyInfo) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *DependencyInfo) GetDependentApp() string {
	if x != nil {
		return x.DependentApp
	}
	return ""
}

func (x *DependencyInfo) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *DependencyInfo) GetSharedResource() string {
	if x != nil {
		return x.SharedResource
	}
	return ""
}

type RemoveResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Success  bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message  string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Blockers []*DependencyInfo      `protobuf:"bytes,3,rep,name=blockers,proto3" json:"blockers,omitempty"`
	Warnings []string               `protobuf:"bytes,4,rep,name=warnings,proto3" json:"warnings,omitempty"`
	// Set when workloads are missing; re-run with force_missing_workloads after user confirms.
	ConfirmRequired bool `protobuf:"varint,5,opt,name=confirm_required,json=confirmRequired,proto3" json:"confirm_required,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RemoveResponse) Reset() {
	*x = RemoveResponse{}
	mi := &file_internal_api_proto_kudo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveResponse) ProtoMessage() {}

func (x *RemoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_proto_kudo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveResponse.ProtoReflect.Descriptor instead.
func (*RemoveResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_proto_kudo_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RemoveResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RemoveResponse) GetBlockers() []*DependencyInfo {
	if x != nil {
		return x.Blockers
	}
	return nil
}

func (x *RemoveResponse) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

func (x *RemoveResponse) GetConfirmRequired() bool {
	if x != nil {
		return x.ConfirmRequired
	}
	return false
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppName       string                 `protobuf:"bytes,1,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_internal_api_proto_kudo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_proto_kudo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_proto_kudo_proto_rawDescGZIP(), []int{5}
}

func (x *StatusRequest) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

type StatusResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AppName         string                 `protobuf:"bytes,1,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	Adapter         string                 `protobuf:"bytes,2,opt,name=adapter,proto3" json:"adapter,omitempty"`
	DesiredReplicas int32                  `protobuf:"varint,3,opt,name=desired_replicas,json=desiredReplicas,proto3" json:"desired_replicas,omitempty"`
	RunningReplicas int32                  `protobuf:"varint,4,opt,name=running_replicas,json=runningReplicas,proto3" json:"running_replicas,omitempty"`
	Instances       []*InstanceInfo        `protobuf:"bytes,5,rep,name=instances,proto3" json:"instances,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_internal_api_proto_kudo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_proto_kudo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_proto_kudo_proto_rawDescGZIP(), []int{6}
}

func (x *StatusResponse) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *StatusResponse) GetAdapter() string {
	if x != nil {
		return x.Adapter
	}
	return ""
}

func (x *StatusResponse) GetDesiredReplicas() int32 {
	if x != nil {
		return x.DesiredReplicas
	}
	return 0
}

func (x *StatusResponse) GetRunningReplicas() int32 {
	if x != nil {
		return x.RunningReplicas
	}
	return 0
}

func (x *StatusResponse) GetInstances() []*InstanceInfo {
	if x != nil {
		return x.Instances
	}
	return nil
}

type InstanceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstanceInfo) Reset() {
	*x = InstanceInfo{}
	mi := &file_internal_api_proto_kudo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceInfo) ProtoMessage() {}

func (x *InstanceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_proto_kudo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceInfo.ProtoReflect.Descriptor instead.
func (*InstanceInfo) Descriptor() ([]byte, []int) {
	return file_internal_api_proto_kudo_proto_rawDescGZIP(), []int{7}
}

func (x *InstanceInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InstanceInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *InstanceInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *InstanceInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type ListNodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesRequest) Reset() {
	*x = ListNodesRequest{}
	mi := &file_internal_api_proto_kudo_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesRequest) ProtoMessage() {}

func (x *ListNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_proto_kudo_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesRequest.ProtoReflect.Descriptor instead.
func (*ListNodesRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_proto_kudo_proto_rawDescGZIP(), []int{8}
}

type ListNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*NodeInfo            `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesResponse) Reset() {
	*x = ListNodesResponse{}
	mi := &file_internal_api_proto_kudo_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesResponse) ProtoMessage() {}

func (x *ListNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_proto_kudo_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesResponse.ProtoReflect.Descriptor instead.
func (*ListNodesResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_proto_kudo_proto_rawDescGZIP(), []int{9}
}

func (x *ListNodesResponse) GetNodes() []*NodeInfo {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type NodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_internal_api_proto_kudo_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_proto_kudo_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_internal_api_proto_kudo_proto_rawDescGZIP(), []int{10}
}

func (x *NodeInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NodeInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NodeInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *NodeInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListAppsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAppsRequest) Reset() {
	*x = ListAppsRequest{}
	mi := &file_internal_api_proto_kudo_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAppsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAppsRequest) ProtoMessage() {}

func (x *ListAppsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_proto_kudo_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAppsRequest.ProtoReflect.Descriptor instead.
func (*ListAppsRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_proto_kudo_proto_rawDescGZIP(), []int{11}
}

type ListAppsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Apps          []*AppInfo             `protobuf:"bytes,1,rep,name=apps,proto3" json:"apps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAppsResponse) Reset() {
	*x = ListAppsResponse{}
	mi := &file_internal_api_proto_kudo_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAppsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAppsResponse) ProtoMessage() {}

func (x *ListAppsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_proto_kudo_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAppsResponse.ProtoReflect.Descriptor instead.
func (*ListAppsResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_proto_kudo_proto_rawDescGZIP(), []int{12}
}

func (x *ListAppsResponse) GetApps() []*AppInfo {
	if x != nil {
		return x.Apps
	}
	return nil
}

type AppInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Adapter       string                 `protobuf:"bytes,2,opt,name=adapter,proto3" json:"adapter,omitempty"`
	Replicas      int32                  `protobuf:"varint,3,opt,name=replicas,proto3" json:"replicas,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppInfo) Reset() {
	*x = AppInfo{}
	mi := &file_internal_api_proto_kudo_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppInfo) ProtoMessage() {}

func (x *AppInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_proto_kudo_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppInfo.ProtoReflect.Descriptor instead.
func (*AppInfo) Descriptor() ([]byte, []int) {
	return file_internal_api_proto_kudo_proto_rawDescGZIP(), []int{13}
}

func (x *AppInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AppInfo) GetAdapter() string {
	if x != nil {
		return x.Adapter
	}
	return ""
}

func (x *AppInfo) GetReplicas() int32 {
	if x != nil {
		return x.Replicas
	}
	return 0
}

func (x *AppInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ScaleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppName       string                 `protobuf:"bytes,1,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	Replicas      int32                  `protobuf:"varint,2,opt,name=replicas,proto3" json:"replicas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScaleRequest) Reset() {
	*x = ScaleRequest{}
	mi := &file_internal_api_proto_kudo_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScaleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScaleRequest) ProtoMessage() {}

func (x *ScaleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_proto_kudo_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScaleRequest.ProtoReflect.Descriptor instead.
func (*ScaleRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_proto_kudo_proto_rawDescGZIP(), []int{14}
}

func (x *ScaleRequest) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *ScaleRequest) GetReplicas() int32 {
	if x != nil {
		return x.Replicas
	}
	return 0
}

type ScaleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScaleResponse) Reset() {
	*x = ScaleResponse{}
	mi := &file_internal_api_proto_kudo_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScaleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScaleResponse) ProtoMessage() {}

func (x *ScaleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_proto_kudo_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScaleResponse.ProtoReflect.Descriptor instead.
func (*ScaleResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_proto_kudo_proto_rawDescGZIP(), []int{15}
}

func (x *ScaleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ScaleResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_internal_api_proto_kudo_proto protoreflect.FileDescriptor

const file_internal_api_proto_kudo_proto_rawDesc = "" +
	"\n" +
	"\x1dinternal/api/proto/kudo.proto\x12\x04kudo\"1\n" +
	"\fApplyRequest\x12!\n" +
	"\fyaml_content\x18\x01 \x01(\tR\vyamlContent\"C\n" +
	"\rApplyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"j\n" +
	"\rRemoveRequest\x12!\n" +
	"\fyaml_content\x18\x01 \x01(\tR\vyamlContent\x126\n" +
	"\x17force_missing_workloads\x18\x02 \x01(\bR\x15forceMissingWorkloads\"\x91\x01\n" +
	"\x0eDependencyInfo\x12\x19\n" +
	"\bapp_name\x18\x01 \x01(\tR\aappName\x12#\n" +
	"\rdependent_app\x18\x02 \x01(\tR\fdependentApp\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12'\n" +
	"\x0fshared_resource\x18\x04 \x01(\tR\x0esharedResource\"\xbd\x01\n" +
	"\x0eRemoveResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x120\n" +
	"\bblockers\x18\x03 \x03(\v2\x14.kudo.DependencyInfoR\bblockers\x12\x1a\n" +
	"\bwarnings\x18\x04 \x03(\tR\bwarnings\x12)\n" +
	"\x10confirm_required\x18\x05 \x01(\bR\x0fconfirmRequired\"*\n" +
	"\rStatusRequest\x12\x19\n" +
	"\bapp_name\x18\x01 \x01(\tR\aappName\"\xcd\x01\n" +
	"\x0eStatusResponse\x12\x19\n" +
	"\bapp_name\x18\x01 \x01(\tR\aappName\x12\x18\n" +
	"\aadapter\x18\x02 \x01(\tR\aadapter\x12)\n" +
	"\x10desired_replicas\x18\x03 \x01(\x05R\x0fdesiredReplicas\x12)\n" +
	"\x10running_replicas\x18\x04 \x01(\x05R\x0frunningReplicas\x120\n" +
	"\tinstances\x18\x05 \x03(\v2\x12.kudo.InstanceInfoR\tinstances\"i\n" +
	"\fInstanceInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\"\x12\n" +
	"\x10ListNodesRequest\"9\n" +
	"\x11ListNodesResponse\x12$\n" +
	"\x05nodes\x18\x01 \x03(\v2\x0e.kudo.NodeInfoR\x05nodes\"`\n" +
	"\bNodeInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"\x11\n" +
	"\x0fListAppsRequest\"5\n" +
	"\x10ListAppsResponse\x12!\n" +
	"\x04apps\x18\x01 \x03(\v2\r.kudo.AppInfoR\x04apps\"k\n" +
	"\aAppInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aadapter\x18\x02 \x01(\tR\aadapter\x12\x1a\n" +
	"\breplicas\x18\x03 \x01(\x05R\breplicas\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"E\n" +
	"\fScaleRequest\x12\x19\n" +
	"\bapp_name\x18\x01 \x01(\tR\aappName\x12\x1a\n" +
	"\breplicas\x18\x02 \x01(\x05R\breplicas\"C\n" +
	"\rScaleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xe6\x02\n" +
	"\aKudoAPI\x120\n" +
	"\x05Apply\x12\x12.kudo.ApplyRequest\x1a\x13.kudo.ApplyResponse\x123\n" +
	"\x06Remove\x12\x13.kudo.RemoveRequest\x1a\x14.kudo.RemoveResponse\x126\n" +
	"\tGetStatus\x12\x13.kudo.StatusRequest\x1a\x14.kudo.StatusResponse\x12<\n" +
	"\tListNodes\x12\x16.kudo.ListNodesRequest\x1a\x17.kudo.ListNodesResponse\x12A\n" +
	"\x10ListApplications\x12\x15.kudo.ListAppsRequest\x1a\x16.kudo.ListAppsResponse\x12;\n" +
	"\x10ScaleApplication\x12\x12.kudo.ScaleRequest\x1a\x13.kudo.ScaleResponseB.Z,github.com/mahimsafa/kudo/internal/api/protob\x06proto3"

var (
	file_internal_api_proto_kudo_proto_rawDescOnce sync.Once
	file_internal_api_proto_kudo_proto_rawDescData []byte
)

func file_internal_api_proto_kudo_proto_rawDescGZIP() []byte {
	file_internal_api_proto_kudo_proto_rawDescOnce.Do(func() {
		file_internal_api_proto_kudo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_api_proto_kudo_proto_rawDesc), len(file_internal_api_proto_kudo_proto_rawDesc)))
	})
	return file_internal_api_proto_kudo_proto_rawDescData
}

var file_internal_api_proto_kudo_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_internal_api_proto_kudo_proto_goTypes = []any{
	(*ApplyRequest)(nil),      // 0: kudo.ApplyRequest
	(*ApplyResponse)(nil),     // 1: kudo.ApplyResponse
	(*RemoveRequest)(nil),     // 2: kudo.RemoveRequest
	(*DependencyInfo)(nil),    // 3: kudo.DependencyInfo
	(*RemoveResponse)(nil),    // 4: kudo.RemoveResponse
	(*StatusRequest)(nil),     // 5: kudo.StatusRequest
	(*StatusResponse)(nil),    // 6: kudo.StatusResponse
	(*InstanceInfo)(nil),      // 7: kudo.InstanceInfo
	(*ListNodesRequest)(nil),  // 8: kudo.ListNodesRequest
	(*ListNodesResponse)(nil), // 9: kudo.ListNodesResponse
	(*NodeInfo)(nil),          // 10: kudo.NodeInfo
	(*ListAppsRequest)(nil),   // 11: kudo.ListAppsRequest
	(*ListAppsResponse)(nil),  // 12: kudo.ListAppsResponse
	(*AppInfo)(nil),           // 13: kudo.AppInfo
	(*ScaleRequest)(nil),      // 14: kudo.ScaleRequest
	(*ScaleResponse)(nil),     // 15: kudo.ScaleResponse
}
var file_internal_api_proto_kudo_proto_depIdxs = []int32{
	3,  // 0: kudo.RemoveResponse.blockers:type_name -> kudo.DependencyInfo
	7,  // 1: kudo.StatusResponse.instances:type_name -> kudo.InstanceInfo
	10, // 2: kudo.ListNodesResponse.nodes:type_name -> kudo.NodeInfo
	13, // 3: kudo.ListAppsResponse.apps:type_name -> kudo.AppInfo
	0,  // 4: kudo.KudoAPI.Apply:input_type -> kudo.ApplyRequest
	2,  // 5: kudo.KudoAPI.Remove:input_type -> kudo.RemoveRequest
	5,  // 6: kudo.KudoAPI.GetStatus:input_type -> kudo.StatusRequest
	8,  // 7: kudo.KudoAPI.ListNodes:input_type -> kudo.ListNodesRequest
	11, // 8: kudo.KudoAPI.ListApplications:input_type -> kudo.ListAppsRequest
	14, // 9: kudo.KudoAPI.ScaleApplication:input_type -> kudo.ScaleRequest
	1,  // 10: kudo.KudoAPI.Apply:output_type -> kudo.ApplyResponse
	4,  // 11: kudo.KudoAPI.Remove:output_type -> kudo.RemoveResponse
	6,  // 12: kudo.KudoAPI.GetStatus:output_type -> kudo.StatusResponse
	9,  // 13: kudo.KudoAPI.ListNodes:output_type -> kudo.ListNodesResponse
	12, // 14: kudo.KudoAPI.ListApplications:output_type -> kudo.ListAppsResponse
	15, // 15: kudo.KudoAPI.ScaleApplication:output_type -> kudo.ScaleResponse
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_internal_api_proto_kudo_proto_init() }
func file_internal_api_proto_kudo_proto_init() {
	if File_internal_api_proto_kudo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_api_proto_kudo_proto_rawDesc), len(file_internal_api_proto_kudo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_api_proto_kudo_proto_goTypes,
		DependencyIndexes: file_internal_api_proto_kudo_proto_depIdxs,
		MessageInfos:      file_internal_api_proto_kudo_proto_msgTypes,
	}.Build()
	File_internal_api_proto_kudo_proto = out.File
	file_internal_api_proto_kudo_proto_goTypes = nil
	file_internal_api_proto_kudo_proto_depIdxs = nil
}
